version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalogapi:
    image: eventbrite/catalogapi
    build:
      context: .\EventCatalog
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:6081
    ports:
      - "6081:80"
    container_name: eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  eventtokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: eventbrite/tokenapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5209
    ports:
      - "6071:80"
    container_name: eventstokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: eventbrite/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.8:6071
      ConnectionString: basket.data
    ports:
      - "5066:80"
    container_name: eventscartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - eventtokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: jewels/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.8:6071
      SQLSERVER_HOST: mssqlserver
      SA_PASSWORD: ProductApi(!)
      DATABASE: OrdersDb
    ports:
      - "6085:80"
    container_name: eventsorderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - eventtokenserver
      - rabbitmq

  
  webmvc:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: eventbrite/webmvc
    container_name: webshopcontainer
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      CatalogUrl: http://eventcatalogapi
      PictureUrl: http://localhost:6081
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.8:6071
      CallBackUrl: http://localhost:5209
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_bYEDa1gq58OOdoqhz0Mp4xBY00G8ruVkpW
      StripePrivateKey: sk_test_ujEJlcmUbIZGEs1Q1PbVDsyp004eQC30LX
    ports:
      - "5209:80"
    networks:
      - frontend
    depends_on:
      - eventcatalogapi
      - eventtokenserver
      - cart
      - order

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    container_name: eventssqlserver
    ports:
      - "1449:1433"
    networks:
      - backend


  basket.data:
    image: redis
    ports:
      - "6076:6379"  
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: eventrabbitmq
    hostname: myrabbitmq
    ports:
      - "15682:15672"
      - "5682:5672"
      - "5681:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend